### ISSUE TITLE
Fehler beim Selektieren Package

### ISSUE THREAD

**Issue by lessingsmatula** [saugstauberr/ToolScope-for-EuroScope#14]
Wenn ich wie auf dem Screenshot dargestellt auf einen Eintrag aus der Dropbox Package drücke, kommt in der Sekunde dieser Fehler. Er ist unabhängig von den gewählten Einstellungen.

System.FormatException: Die von der Zeichenfolge dargestellte DateTime wird in Kalender System.Globalization.GregorianCalendar nicht unterstützt.
   bei System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   bei ToolScope_for_EuroScope.Main.packagebox_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
![FehlerScreenshot](https://github.com/saugstauberr/ToolScope-for-EuroScope/assets/155357407/447a1c23-f5a8-42a3-a21c-a6ee76ac9fe0)

**Comment by airxiti** [comment]
Hab das gleiche Problem mit der gleichen Fehlermeldung

**Comment by saugstauberr** [comment]
Hallo @airxiti @lessingsmatula ,

vielen Dank für das Issue. Aktuell bin ich leider etwas inaktiver an diesem Projekt am Arbeiten, deswegen bitte ich um etwas Geduld. Aber mit dem nächsten großen Update ist das auf jeden Fall gefixxt. :)

**Comment by saugstauberr** [comment]
Fixed. Thank you!
