### ISSUE TITLE
AIRAC missing

### ISSUE THREAD

**Issue by RudiZhang** [saugstauberr/ToolScope-for-EuroScope#3]
![image](https://github.com/saugstauberr/ToolScope-for-EuroScope/assets/40914896/5ec98f52-5c26-456d-93da-122cf281142d)

as above, there is no way to select AIRAC after LEXX

**Comment by saugstauberr** [comment]
Having the same problem, gonna fix it asap. Thank you for reporting! :)

**Comment by saugstauberr** [comment]
Should be fixed. Gonna change the config file from .ini to a .json file for better compatibility soon, so it's just an easy quick fix.
