### ISSUE TITLE
Can't install multiple packages from one region

### ISSUE THREAD

**Issue by Jannis-D** [saugstauberr/ToolScope-for-EuroScope#7]
Can't install multiple packages from one region

Example: EDXX - EDWW - RG Berlin and RG Bremen Packs not working - overwriting themself.

- v1.4.2

**Comment by saugstauberr** [comment]
Hi, thank you for you issue.

That's probably because there are now 2 different EDWW packages. Previously there was only 1 EDWW package with 2 variants (Full-Package and Update). So it was useful when you could only install one of them.

Gonna fix this issue asap.
